### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by jason-henriksen** [vision10/mssql-ssrs#1]
Hello, I'm very hopeful about this effort!   I'm curious about a couple of things:

1) Can this be used to run reports ( similar to the iframe/URL method of running reports ) but with more customizable security?

2) does the URL of the report server have to be publicly available?  Or is it possible to run SSRS such that the soap service is available and can use authentication, but the ability to access report by url is not available.

3) if I render the report, how do I specify where the resulting report HTML should be rendered?

Thanks for any clarifications.

            - Jason

**Comment by vision10** [comment]
1. yes you can render reports using microsoft reporting services api with multiple types of security (limited to soaps knows security types and microsoft reporting server), default security is ntlm. 
Theres also a method to run reports using url (creates the url and makes a request) but right now its limited to ntml requests, I could modify it to use ntlm/normal request

2. not sure if I understood correctly but I could restrict the soap service to just the createClient so the url wont be available except for in the package. I could also restrict access to the report by url method via options on start

3. rendering reports with getReport returns the completed report in a base64 string and getReportByUrl returns a binary

I hope that clarifies it
