### ISSUE TITLE
Can't get reports on MSSQL Server 2017

### ISSUE THREAD

**Issue by DenisBessa** [vision10/mssql-ssrs#12]
Hi,

I'm getting an undefinied response with the listChildren.

```
const ssrs = require("mssql-ssrs");

async function loginServer() {
  try {
    const config = { username: "test", password: "test" };
    await ssrs.start(
      "https://myserver.com/ReportServer",
      config,
      null,
      "basic"
    );

    var reportList = await ssrs.reportService.listChildren("/", true);

    console.log(reportList);
  } catch (error) {
    console.log(error);
  }
}

loginServer();
```

Help, please!

**Comment by vision10** [comment]
The only time I have been able to get a null is when there are no items in the path/folder provided but its not an error, that is the result is from the server, there are no extra manipulations.
Also if the path does not exist it throws an error
Maybe it would help to always return an array?
