### ISSUE TITLE
It will support NTML 2 ?

### ISSUE THREAD

**Issue by Rajesh-jai** [vision10/mssql-ssrs#14]
DB system "Network Security: LAN Manager authentication level" configured as "Send NTLMv2 response only/refuse LM & NTLM" When I trying to start the connection getting  Error: Error http status codes

**Comment by vision10** [comment]
It will support NTML 2 - I dont know, I need to study a bit.

On another note a [pull request](https://github.com/vpulim/node-soap/pull/1146) for [soap](https://github.com/vpulim/node-soap) was recenly accepted (replacing `httpntlm` with `axios-ntlm`), so I am planning an update soon.

Maybe an axios request interceptor could do it?
Any help would be apreciated,

**Comment by jjateveri** [comment]
Hello,
Just wanted to mention that after changing to the axios library it seems that NTLMv2 appears to be working against active directory. I tested against v2.0.3

**Comment by Nirator78** [comment]
Everything working find in NTLMv2 too, I think we can close the issue.
