### ISSUE TITLE
Unable to connect to report server

### ISSUE THREAD

**Issue by maheshdatta** [vision10/mssql-ssrs#2]
tried the following -

```
var ssrsConfig = {
	"server": "<server_url>",
	"instance": "<instance_name>",
	"isHttps": false,
	"port": "80"
};

var ssrsAuth = {
	"username": "<user_name>",
	"password": "<password>"
};

async function ssrsInit() {
	try{
		var security = new ssrs.security.BasicAuthSecurity(ssrsAuth.username, ssrsAuth.password);		
		await ssrs.start(ssrsUrl, ssrsAuth);		
		return;
	} catch(err) {
		console.log(err);
	}
}
ssrsInit().then(
	function(arg){
		// TODO: capture any return object
	});
```

But getting an error in the line **await ssrs.start(ssrsUrl, ssrsAuth);** as 

> First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

Could you please provide some guidance on how to connect/ what is being missed here?

**Comment by vision10** [comment]
Other tipes of security than ntlm where not completely treated, it should work now with the latest version
Tried it with:

```js
var ssrsConfig = {"server": "<server_name_not_url>", "<instance_name>" };
var ssrsAuth = { "username": "<user_name>", "password": "<password>" };

async function ssrsInit() {
    try {
        var security = new ssrs.security.BasicAuthSecurity(ssrsAuth.username, ssrsAuth.password);
        await ssrs.start(ssrsConfig, ssrsAuth, options, security);
    } catch (err) { console.log(err) }
}

ssrsInit().then(function (arg) { });
```

username and password were  a local windows user

security is used to get the wsdl and is set after the soap client is created passing it to start
     await ssrs.start(ssrsConfig, ssrsAuth, null, **security**);

**Comment by maheshdatta** [comment]
Getting below error now -

> www-authenticate not found on response of second request

**Comment by maheshdatta** [comment]
Thanks for your response. I was able to get through **await ssrs.start(...);**.
I was trying to get a list of reports from reportpath, but I am getting an error when executing **listChildren**.

`var children = await ssrs.reportService.listChildren("/", true);`

I could see the xml response from "<server_name>/< instance >/ReportService2010.asmx"
as below 

`<wsdl:definitions xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://schemas.microsoft.com/sqlserver/reporting/2010/03/01/ReportServer"> ...`

But the list children call failed with an error saying - 

> Error: Cannot parse response

Please advice.

**Comment by vision10** [comment]
Sorry for the late response
All start methods parameters have been updated to be more consistent 
And all methods should work with other types of security now
