### ISSUE TITLE
Possible to get reports params available and default value to display ?

### ISSUE THREAD

**Issue by Nirator78** [vision10/mssql-ssrs#27]
Hi,
I am currently using your library and I would like to know if it is possible to retrieve the `valid value` and `default values` in the `getReportParams`.

The actual return give me 
`
{
    Name: 'Dossier',
    ParameterTypeName: 'String',
    Nullable: false,
    AllowBlank: false,
    MultiValue: false,
    QueryParameter: true,
    Prompt: 'Dossier',
    PromptUser: true,
    ValidValuesQueryBased: true,
    DefaultValuesQueryBased: false,
    ParameterStateName: 'DynamicValuesUnavailable'
  }
`

But the complete return in a microsoft issue give this:
https://learn.microsoft.com/en-us/answers/questions/1179688/using-the-ssrs-rest-api-how-do-you-get-values-of-a
`
{
"Name":"Range"
,"ParameterType":"String"
,"ParameterVisibility":"Visible"
,"ParameterState":"HasOutstandingDependencies"
,"ValidValues":[]
,"ValidValuesIsNull":true
,"Nullable":false
,"AllowBlank":false
,"MultiValue":false
,"Prompt":"Range"
,"PromptUser":true
,"QueryParameter":false
,"DefaultValuesQueryBased":false
,"ValidValuesQueryBased":true
,"Dependencies":["Township"]
,"DefaultValues":[]
,"DefaultValuesIsNull":true
,"ErrorMessage":null
}
`

The ValidValues and DefaultValues are really import to manage display manually in application.
Maybe i do something bad I let you tell me.

**Comment by Nirator78** [comment]
Sorry, it's because my reporting service was not up to date.

**Comment by vision10** [comment]
Yes, you can get `ValidValues` and `DefaultValues` with

`ssrs.reportService.getReportParams(reportPath)` and 
`ssrs.reportService.updateReportParams(reportPath, params, true)`
