### ISSUE TITLE
createResource function not working

### ISSUE THREAD

**Issue by vishal-chhabria** [vision10/mssql-ssrs#3]
var resurce = await ssrs.reportService.createResource(path, fileContents, mimeType);
 
Above statement throws error as  it uses "name", "parent" and other variables that are not in method declaration. Also, the implementation should user client.CreateCatalogItem to call the soap method however it user client.ClientResource() which again is not found and throws error.

Method definitation and implementation should be as below - 

async function createResource(name, path, fileContents, mimeType) {
    try {
        var resource = await client.CreateCatalogItem({
            ItemType: 'Resource',
            Name: name,
            Parent: path,
            Overwrite: true,
            Definition: fileContents,
            Properties: {
                Property: [
                    { Name: 'MimeType', Value: mimeType }
                ]
            }
        });
        return resource;
    } catch (error) { report.errorHandler(error) }
}

**Comment by vision10** [comment]
Sorry, I messed up when I made that one 
Your solution works, I've updated the package and documentation
