### ISSUE TITLE
INQUIRY Only - Report Execution

### ISSUE THREAD

**Issue by JojiePalahang** [vision10/mssql-ssrs#4]
I just want to understand the feature for Report Execution.

Correct me if I understand it properly.

- SSRS server exposes an API with is SOAP to allow the consumer to generate a report via API?
- Report return as a stream of a byte.

which did I expect when I run this code?

`var reportPath = '/Folder/ReportName';
var fileType = 'word';
var parameters = { 
  parameterName: 'parameterValue', 
  parameterName2: false 
  multiValue: ['value1', 'value2']
};
//or
var parameters = [
  { Name: 'parameterName', Value: 'parameterValue' },
  { Name: 'parameterName2', Value: false }
  { Name: 'multiValue', Value: ['value1', 'value2'] }
]
var report = await ssrs.reportExecution.getReport(reportPath, fileType, parameters)`

Hoping for your kind response.

**Comment by vision10** [comment]
You will get a result like this
```
{
    "Extension":"pdf"
    "MimeType":"application/pdf"
    "Result:" "" // base64 string
    "StreamIds":null
}
```
You will get a base64 string result to manipulate

I just create a file in some directory
fs.writeFile('/path/reportname', report.Result, "base64")

**Comment by JojiePalahang** [comment]
@vision10  - Thanks a lot, closing this ticket.
