### ISSUE TITLE
Unable to generate Report

### ISSUE THREAD

**Issue by JojiePalahang** [vision10/mssql-ssrs#5]
@vision10  - Previously my reports work fine but now I'm facing this issue.

Error: www-authenticate not found on response of second request - any idea what this error?

**Comment by rcmedeiros** [comment]
same with me

**Comment by vision10** [comment]
That error is thrown when the report server url is not valid

**Comment by JojiePalahang** [comment]
@vision10  - you mean issues is not code related but the server issue. we can now close this issue.
