### ISSUE TITLE
Multi-value array is not read correctly due to lower case values reference.

### ISSUE THREAD

**Issue by TylerSchroeder** [vision10/mssql-ssrs#6]
In reportExecution.js on line 144 there is a lower case v that needs to be uppercase. Using a lower case v results in undefined values from the multi-select. 

` else {
                for (var j = 0; j < params[i].Value.length; j++) {
                    formated.push({
                        Name: params[i].Name,
                        Value: params[i].value[j]
                    });
                }
            }`

` else {
                for (var j = 0; j < params[i].Value.length; j++) {
                    formated.push({
                        Name: params[i].Name,
                        Value: params[i].Value[j]
                    });
                }
            }`

Prior to making this change in my local npm package, I broke out my multi-part to match the example in the comments and it ran successfully.

`{ field: value }
for multivalue { sameField: [value1, value2] } =>
  [
       { Name: sameField, Value: value1 },
       { Name: sameField, Value: value2 }
  ]`

**Comment by TylerSchroeder** [comment]
Issue Resolved. Thanks

**Comment by vision10** [comment]
Happy to help and thanks for spotting this issue
