### ISSUE TITLE
Readme should have a more explicit NTLM example.

### ISSUE THREAD

**Issue by epiphanizer** [vision10/mssql-ssrs#8]
As NTLM is the default SSRS authentication mechanism, the readme should really include an explicit example of that. We were unable to get this working and the documentation online is super sparse for what seems should be such a common feature. Not all of us can enable basic auth on the host machine.

**Comment by vision10** [comment]
I will write/expand a some examples in the readme in a few days

**Comment by praveenpenmetsa** [comment]
Can you also add some examples for angular.... Would like to see a simple example in angular Where you get a report by passing( url,parameters, auth) to display on the page .

**Comment by vision10** [comment]
This package was not intended for client side or use with other frameworks (it might work but I did not use it like that), for that reason it also does not have anything to deal with CORS.
