### ISSUE TITLE
Error in getReportByUrl + SSRS 2017

### ISSUE THREAD

**Issue by zantonz2** [vision10/mssql-ssrs#9]
Trying to connect to SRS 2017, the getReportByUrl method throws an error. The description specifies username in the userName code, but getReportByUrl cannot be executed.

await ssrs.reportExecution.getReportByUrl(path, type, params, {userName: ''test, password: 'test'})

Sorry for my English

**Comment by vision10** [comment]
I need a bit more info about your error or a more complete example to answer 
This is an example of how I use it:

```js 
const ssrs = require('mssql-ssrs');

// must set server url
var serverUrl = 'http://<serverName:port>/ReportServer_<InstanceName>"'
ssrs.setServerUrl(serverUrl);

var format = 'pdf';
var reportPath = '/folder/reportname';
var params = { paramName: paramValue };
var auth = { userName: 'test', password: 'test' };

var report = await ssrs.reportExecution.getReportByUrl(reportPath, format, params, auth);

fs.writeFile(path, report); 
```

`getReportByUrl` does not require `ssrs.reportExecution.start()`, but you have to set the `serverUrl`

Hope this helps you.
